// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycledRushDriveTrain.subsystems;

import org.usfirst.frc692.RecycledRushDriveTrain.Robot;
import org.usfirst.frc692.RecycledRushDriveTrain.RobotMap;
import org.usfirst.frc692.RecycledRushDriveTrain.commands.*;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController leftFrontTalon0 = RobotMap.driveTrainleftFrontTalon0;
    SpeedController leftBackTalon1 = RobotMap.driveTrainleftBackTalon1;
    SpeedController rightFrontTalon2 = RobotMap.driveTrainrightFrontTalon2;
    SpeedController rightBackTalon3 = RobotMap.driveTrainrightBackTalon3;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    Gyro gyro = RobotMap.driveTrainGyro;
    Encoder leftFrontEncoder = RobotMap.driveTrainleftFrontEncoder;
    Encoder leftBackEncoder = RobotMap.driveTrainleftBackEncoder;
    Encoder rightFrontEncoder = RobotMap.driveTrainrightFrontEncoder;
    Encoder rightBackEncoder = RobotMap.driveTrainrightBackEncoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveFieldCentric());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    /*mecanumDrive_Cartesian(double x, double y, double rotation, double gyroAngle)
     * x: The speed that the robot should drive in the X direction [-1.0, 1.0]
     * y: The speed that the robot should drive in the Y direction.
     * This input is inverted to match the forward == -1.0 that joysticks produce. [-1.0..1.0]
     * rotation: The rate of rotation for the robot that is completely independent of the translation. [-1.0..1.0]
     * gyroAngle: The current angle reading from the gyro. Use this to implement field-oriented controls.
     */
    
    public void moveForward() {
    	robotDrive.mecanumDrive_Cartesian(0.0, 1.0, 0.0, 0.0);
    }
    // moves all motors in the forward direction
    // EV 1/12/15
    
    public void moveBackward() {
    	robotDrive.mecanumDrive_Cartesian(0.0, -1.0, 0.0, 0.0);
    }
    // moves all motors in the backward direction
    // EV 1/12/2015
    
    public void moveLeft() {
    	robotDrive.mecanumDrive_Cartesian(-1.0, 0.0, 0.0, 0.0);
    }
    // moves all motors in the left direction
    // EV 1/12/2015
    
    public void moveRight() {
    	robotDrive.mecanumDrive_Cartesian(1.0, 0.0, 0.0, 0.0);
    }
    // moves all motors in the right direction
    // EV 1/12/2015
  
    public void takeJoystickValueGyro(double xaxis, double yaxis, double rotate, double gyro) {
    	robotDrive.mecanumDrive_Cartesian(xaxis, yaxis, rotate, gyro);
    }
    // made a constructor to get values of joystick to drive in one direction WITH GYRO
    // EV 1/15/2015
    
    public void takeJoystickValueDefault(double xaxis, double yaxis, double rotate) {
    	robotDrive.mecanumDrive_Polar(xaxis, xaxis, rotate);
    // made a constructor to get values of joystick to drive in one direction WITHOUT GYRO
    // EV 1/15/2015
    }
}
